# Generated by Django 4.2.13 on 2024-07-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginsystem", "0002_alter_course_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="course",
        ),
        migrations.AddField(
            model_name="profile",
            name="courses",
            field=models.ManyToManyField(to="loginsystem.course"),
        ),
    ]
