# Generated by Django 4.2.13 on 2024-07-01 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("loginsystem", "0003_remove_profile_course_profile_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
