# Generated by Django 4.2.13 on 2024-07-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginsystem", "0004_profile_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="date",
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(default=None, upload_to=""),
        ),
    ]
