# Generated by Django 4.2.13 on 2024-07-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loginsystem", "0005_remove_profile_date_profile_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="profile_picture",
        ),
    ]
