# Generated by Django 4.2.13 on 2024-07-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_chapters_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapters",
            name="path",
            field=models.CharField(max_length=100),
        ),
    ]
