# Generated by Django 4.2.13 on 2024-07-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_chapters_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapters",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
