# Generated by Django 4.2.13 on 2024-07-10 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0004_chapters_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapters",
            name="completed",
        ),
        migrations.AddField(
            model_name="chapters",
            name="completed_by",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
